### ISSUE TITLE
Tab menu issues on DarkRP

### ISSUE THREAD

**Issue by TontonBa** [FPtje/DarkRP#2342] opened 2016-02-24 22:35 UTC
So, i created Darkrp server, installed the lastest updates and when i join and set me as superadmin via console "rcon ulx adduserid..." i get in the superadmin group and can use the menu and execute commands but when i'm on the tab menu have none of the commands (ban, kick, freeze...) and when i try to go on server settings it says "no access!".

Itried everything but nothing happen :/

[Screenshots]
http://www.noelshack.com/2016-08-1456348942-tabmenu.png
http://www.noelshack.com/2016-08-1456348941-tabmenu.png
http://www.noelshack.com/2016-08-1456348941-ulxmenu.png

**Comment by BillyOnWiiUIn144p** [comment] 2016-02-24 23:24
The tab menu is FAdmin, not ULX. They are two different admin mods.

**Comment by TontonBa** [comment] 2016-02-24 23:25
I know but why i can't have the commands on tab menu ?
Like before because before i have access to all things but now nothing..

**Comment by HDG-MrDeeJay** [comment] 2016-02-24 23:26
But wasn't Cami supposed to fix this?

**Comment by deinemudda32** [comment] 2016-02-25 12:15
Didnt I reported this already? :D

**Comment by TontonBa** [comment] 2016-02-25 13:44
Don't know :( i'm gonna check :/

**Comment by TontonBa** [comment] 2016-02-25 14:00
@Dein

But do actualy someone find how to fix it ?

**Comment by TontonBa** [comment] 2016-02-25 14:16
@deinemudda32 

Don't know :( i'm gonna check :/
But do actualy someone find how to fix ?

**Comment by FPtje** [comment] 2016-02-25 17:22
Duplicate of #2341

**Closed by FPtje** 2016-02-25 17:22 UTC

**Comment by FPtje** [comment] 2016-02-25 20:39
Oh, this issue is different. It's not my responsibility, though, it's ULX':

```
] lua_run_cl print(Player(3):GetNWString("usergroup"))
user
] lua_run_cl print(Player(3):GetUserGroup())
superadmin
] lua_run_cl show(FindMetaTable("Player").GetUserGroup)
function: 0x2b9d5b10	-- [addons/ulib/lua/ulib/shared/sh_ucl.lua]: 263-272
] lua_run print(Player(3):GetUserGroup())
> print(Player(3):GetUserGroup())...
user
```

ULib has overridden GetUserGroup and decided that clientside it should say "superadmin" while serverside it says "user". FAdmin uses GetUserGroup, so clientside, the player thinks they're superadmin.

**Comment by TontonBa** [comment] 2016-02-25 20:49
No prob, but what i have to do ? :/, i'm begining and don't know big things about that.

**Comment by FPtje** [comment] 2016-02-25 20:56
Call in @Ulysses I guess

**Comment by FPtje** [comment] 2016-02-25 20:57
Not the ulysses I meant, I meant @TeamUlysses
Sorry, @Ulysses for calling you into this thread. If you don't know Garry's mod, you should try it.

**Comment by TontonBa** [comment] 2016-02-25 21:00
Thanks for the help <3
