### ISSUE TITLE
Cam function override has an error

### ISSUE THREAD

**Issue by thegrb93** [FPtje/DarkRP#2705] opened 2017-10-22 21:46 UTC
https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/workarounds/sh_workarounds.lua#L106

Needs to also incorporate cam.Start and cam.End or else bad stuff happens. Or just remove these overrides.

Causes https://github.com/thegrb93/StarfallEx/issues/312

Code to reproduce
```lua
cam.Start{ type = "3D" }
cam.End3D()
```

**Comment by Kefta** [comment] 2017-10-22 22:13
Also, why does this utilise hardcoded arguments instead of varargs?

**Comment by thegrb93** [comment] 2017-10-22 22:18
I think varargs is slower

**Comment by Kefta** [comment] 2017-10-22 22:28
I think JIT negates it if the varargs are never actually touched except to pass right through. Either way, this override is definitely not about speed, and varargs are used in other places in the same file

**Comment by thegrb93** [comment] 2017-10-22 22:31
Just tested and vararg seems to be faster actually.

**Comment by FPtje** [comment] 2017-10-23 03:54
Holy shit, I never knew you could pass a type to cam.Start. Oh well, has that crash been fixed in Gmod yet?

**Comment by FPtje** [comment] 2017-10-23 03:57
Btw, there's more wrong in that function: it hides what's clearly an error situation. You could write bad code, have it work in DarkRP and never find out there's something wrong with it.

**Comment by Kefta** [comment] 2017-10-23 04:03
Nope https://github.com/Facepunch/garrysmod-issues/issues/1091

**Comment by FPtje** [comment] 2017-10-27 17:01
please test

**Closed** 2017-10-27 17:01 UTC

**Comment by Kefta** [comment] 2017-10-27 17:09
There's a few issues:  you aren't overriding Start3D and Start2D anymore so they won't increment the counter. Next, you aren't passing the args through from your overrided functions anymore so your override could potentially affect the output/behaviour of another override. You did it with cam.Start but not the rest. Lastly, 3D cam and 2D cam have separate stacks of render instances - incrementing the same counter would not stop crashes of someone did:

```
cam.Start({type = "3D"})
cam.End2D()
```

**Comment by FPtje** [comment] 2017-10-27 17:18
I'm not overriding `cam.Start3D` and `cam.Start2D` because it would increment the counter twice as they are defined in terms of `cam.Start` in `lua/includes/extensions/client/render.lua`. Overriding them would be a mistake. I specifically tested this behaviour, and it works as intended.

`cam.End3D` and `cam.End2D` don't take arguments. I'll give them varargs though, for other overrides.

And the last case is one I acknowledge, but I cba there. This should be good enough until it gets fixed properly.

**Comment by Kefta** [comment] 2017-10-27 17:46
Ah, I did not know those functions were implemented in Lua. What about 3D2D?

**Comment by FPtje** [comment] 2017-10-27 17:46
Doesn't seem to crash.

**Comment by Kefta** [comment] 2017-10-27 17:54
Crashes after two calls - seems there is a 3D2D instance there to begin with.

```
lua_run_cl cam.End3D2D() cam.End3D2D()
```

**Comment by FPtje** [comment] 2017-10-27 18:02
ughhhh

I'll just whack in in there with the rest

**Comment by FPtje** [comment] 2017-10-27 18:07
I'm overriding `cam.3D2D` because that one *isn't* defined in terms of `cam.Start`
