### ISSUE TITLE
DarkRP Error with cl_init.lua and items

### ISSUE THREAD

**Issue by josh74717** [FPtje/DarkRP#2654] opened 2017-03-17 15:30 UTC
Hello, I get this error every time I launch the server.

[DarkRP] gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:796: attempt to compare nil with string
  1. unknown - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:796
   2. sort - [C]:-1
    3. mergeCategories - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:896
     4. fn - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:908
      5. Call - addons/ulib/lua/ulib/shared/hook.lua:109
       6. Call - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:149
        7. unknown - gamemodes/darkrp/gamemode/cl_init.lua:53

**Comment by strideynet** [comment] 2017-03-18 12:37
Please use the following format when making issues in future:  
```
Description of the bug

How to make the bug happen

Lua errors

Why the developer of DarkRP is responsible for this issue
```
This issue could be caused by custom configuration, can you please provide more information regarding your setup.

**Comment by Bo98** [comment] 2017-03-18 12:45
Most likely caused by custom configuration, but maybe there's a case here where additional validation would make things clearer.

**Comment by FPtje** [comment] 2017-03-18 12:45
already committed

**Closed** 2017-03-18 12:50 UTC
