### ISSUE TITLE
Door Groups / Jail Positions don't save.

### ISSUE THREAD

**Issue by TheSuspectTS** [FPtje/DarkRP#3077] opened 2021-01-01 11:26 UTC
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Hello again, I'm sorry if I somehow got bored on this issue, but the last appeal did not help me. When I put the door group or put the jail position they are put and work, but when I restart the server everything is reset.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
lua_errors_server.txt: https://pastebin.com/wXPWmHe9 clientside_errors.txt: https://pastebin.com/tWTYEHQC

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I didn't find anything related to loading door groups or jail position in log files. When I write to the console: lua_run a =findmetatable ([[Entity]]) printtable(debug.getinfo(a. entindex)) writes me: [ERROR] lua_run:1: bad argument #1 to 'findmetatable' (string expected, got function)
1. findmetatable - [C]:-1
2. unknown - lua_run:1 When removing addons, the problem does not disappear. And I've already tried everything and I don't know what to do.

**Comment by FPtje** [comment] 2021-01-01 13:17
That `lua_run` command you mention doesn't make much sense to me. In the error log I see problems with `igsmodification`, `bank-robbery-system-master`, `atlaschat`. Any of these individually can be the cause of the problem. I'm closing the issue again. Please don't create new issues. Post in **THIS** issue.

**Closed by FPtje** 2021-01-01 13:17 UTC
