### ISSUE TITLE
Shipments "allowed" field doesn't apply to seperate guns

### ISSUE THREAD

**Issue by Partixel** [FPtje/DarkRP#1936] opened 2015-05-19 17:03 UTC
To quote the wiki:
```lua
allowed = {TEAM_GUN, TEAM_MEDIC}, -- OPTIONAL, which teams are allowed to buy this shipment/separate gun
```

Only works with shipments, anyone can buy the singular versions, using the latest version of darkrp + default F4 menu

**Comment by Partixel** [comment] 2015-05-19 17:10
You can replicate the issue with a clean install and the example shipment from http://wiki.darkrp.com/index.php/DarkRP:CustomShipmentFields

**Comment by Bo98** [comment] 2015-05-19 17:20
Try setting GM.Config.restrictbuypistol to true. I believe the comment for it is incorrect.

**Comment by Partixel** [comment] 2015-05-19 17:23
No, that made only the gun dealer able to buy it.

**Comment by Bo98** [comment] 2015-05-19 17:34
> I believe the comment for it is incorrect.

or did you try it?

**Comment by Partixel** [comment] 2015-05-19 17:37
I just tried it, :)

**Comment by Partixel** [comment] 2015-05-20 14:04
Oh, and a side note, the customCheck function *does* work for separate weapons

**Comment by TheEMP** [comment] 2015-05-20 15:18
Its because this function does not check for allowed teams. 
https://github.com/FPtje/DarkRP/blob/6d56fe2d1a0e2858000cb8192fb45eb42ccf7270/gamemode/modules/base/sv_purchasing.lua#L1

I'd make a pull request to fix it but I'm not sure of thats how Falco intended to to be.

**Comment by Partixel** [comment] 2015-05-20 15:36
Well, that's why I made this issue :)

**Comment by FPtje** [comment] 2015-05-20 18:31
Back when I made the shipments, I made a mistake. I made it so that shipments and separetely sold weapons are "*kind of the same thing*". The problem is that they aren't the same thing. The idea was that you could make a shipment that was to be sold by the gundealer only, but then say "*Oh this can also be sold separately by anyone*". That is why by default, the separate guns can be bought by anyone.

Later I heard people wanting to restrict the separate guns to teams as well, so I made the option `GM.Config.restrictbuypistol`. When set to true, DarkRP **will** check for the allowed field when buying separate guns. ([checked in this code](https://github.com/FPtje/DarkRP/blob/6d56fe2d1a0e2858000cb8192fb45eb42ccf7270/gamemode/modules/base/sv_purchasing.lua#L23))

If I could change this behaviour, I would make a separate function for `DarkRP.createWeapon` and strip the separate weapon bit from shipments. I can't do this because it would *massively* break backwards compatibility. I'd break everyone's shipments **and** every addon that does anything with shipments and/or separate guns.

**Closed by FPtje** 2015-05-20 18:31 UTC

**Comment by HDG-MrDeeJay** [comment] 2015-05-20 18:33
they say hindsight is 20/20

**Comment by Partixel** [comment] 2015-05-20 18:37
Could've sworn I tested Gm.Config.restrictbuypistol when @Bo98 mentioned it and it didn't work. Either way, nice config setting.

**Comment by FPtje** [comment] 2015-05-20 18:39
@Partixel You said it was restricted to the gundealer. This is impossible. Over the years I've changed DarkRP in such a way that there are no more hardcoded references to any jobs in any of the code anymore. That allows you to remove all default jobs and create your own and have all the DarkRP features work with those instead.

**Comment by Partixel** [comment] 2015-05-20 18:40
I know, I realise this, like I said, when I tested it earlier I could've sworn that's what it behaved as, although knowing me I probably fucked something up.

**Comment by Partixel** [comment] 2015-05-20 18:41
Might want to make the description for that config setting a bit more clear

**Comment by HDG-MrDeeJay** [comment] 2015-05-20 18:42
whats unclear about it? It enables restrictions on buying individual 
weapons. Pretty simple to me.

**Comment by Partixel** [comment] 2015-05-20 18:43
'''lua
Enabling this feature makes /buy available only to Gun Dealers.
'''
The "Gun Dealers" part

**Comment by HDG-MrDeeJay** [comment] 2015-05-20 18:44
well ok that description is old.

Should end up being something like "Enabling this feature enables team 
checks on individual weapons."

**Comment by Partixel** [comment] 2015-05-20 18:48
enables *allowed* checks on individual weapons, or something indicating it restricts the use of the allowed table

**Comment by HDG-MrDeeJay** [comment] 2015-05-20 18:49
How about "Allows you to travel at 20x the speed of light, but only in 
reverse."

**Comment by Partixel** [comment] 2015-05-20 18:51
Sounds good, but maybe "and turns you into a lizard" just to be accurate

**Comment by HDG-MrDeeJay** [comment] 2015-05-20 18:54
Pfft, lizard? I'd rather be a racoon.

**Comment by Partixel** [comment] 2015-05-20 18:56
Well, if it was up to us you could be whatever you want, but it's up to the 20,000 year old Japanese monks that we used to be.
