### ISSUE TITLE
Error in fn.lua - Line 2: unexpected currying expecting indexation or function call

### ISSUE THREAD

**Issue by DanielArguirov** [FPtje/DarkRP#3154] opened 2021-11-09 20:39 UTC
Function currying
    Take a function with n parameters.
    Currying is the procedure of storing k < n parameters "in the function"
     in such a way that the remaining function can be called with n - k parameters

    Example:
    DebugPrint = fp{print, "[DEBUG]"}
    DebugPrint("TEST")
    > [DEBUG] TEST
    
    https://fptje.github.io/glualint-web/ to see if any errors are in the lua

**Comment by FPtje** [comment] 2021-11-09 20:51
Yeah I know. I wrote that library. What's the point of this issue?

**Comment by Kefta** [comment] 2021-11-09 21:37
Check the stack trace for what is actually causing the error.

**Comment by FPtje** [comment] 2021-11-09 22:12
Oooh it's just a copy paste of the comment in that file. I was wondering why someone would be able to explain the concept of currying while not knowing how to report an error. 

I'll close the issue as invalid. This error is likely enough caused by a user error.

**Closed by FPtje** 2021-11-09 22:12 UTC
