### ISSUE TITLE
Unable to set doorgroup

### ISSUE THREAD

**Issue by jdhk94** [FPtje/DarkRP#2162] opened 2015-09-15 11:30 UTC
Trying to set a custom door group, gets error "Door group does not exist" using this code:
https://gyazo.com/1796653729648768a6e3fd06cf937e25

![2015-09-15_00004](https://cloud.githubusercontent.com/assets/12697419/9875374/b5cf6002-5bad-11e5-8863-169ab42db4cc.jpg)
![2015-09-15_00005](https://cloud.githubusercontent.com/assets/12697419/9875375/b5cfee78-5bad-11e5-9898-6f6eac83cf2e.jpg)

**Comment by fruitwasp** [comment] 2015-09-15 13:14
You got the latest darkrp build?

**Comment by jdhk94** [comment] 2015-09-15 13:16
Downloaded it yesterday so I guess..?

**Comment by fruitwasp** [comment] 2015-09-15 13:21
Download the latest build and tell us if you still experience the problem

**Comment by jdhk94** [comment] 2015-09-15 13:22
Alright, only darkRP? Or darkrpmodification too?

**Comment by fruitwasp** [comment] 2015-09-15 13:23
Only darkrp

**Comment by jdhk94** [comment] 2015-09-15 13:44
Updated and still the same error.

**Comment by FPtje** [comment] 2015-09-15 13:44
Working on it

**Comment by FPtje** [comment] 2015-09-15 13:48
Should be fixed in latest now.

**Closed by FPtje** 2015-09-15 13:48 UTC

**Comment by jdhk94** [comment] 2015-09-15 14:03
Still not working for me

**Comment by FPtje** [comment] 2015-09-15 14:14
![2015-09-15_16-14-25](https://cloud.githubusercontent.com/assets/1202014/9878809/dd3bd384-5bc4-11e5-97ae-6b78f2f7a6b9.jpg)

Works for me.

**Comment by jdhk94** [comment] 2015-09-15 14:21
Even the original ones do not work for me
![2015-09-15_00006](https://cloud.githubusercontent.com/assets/12697419/9879024/dfb76c8a-5bc5-11e5-86ef-f3223232a875.jpg)

**Comment by FPtje** [comment] 2015-09-15 14:22
It's your screenshot versus mine.

**Comment by jdhk94** [comment] 2015-09-15 14:23
I'm just trying to get this to work.. Not judging..

**Comment by FrikenCanadiansEH** [comment] 2015-09-15 14:23
@jdhk94 Try it on a fresh server install

**Comment by FPtje** [comment] 2015-09-15 14:23
I cannot fix bugs that I cannot reproduce.
