### ISSUE TITLE
Create doors, jails do not save. help please

### ISSUE THREAD

**Issue by TheSuspectTS** [FPtje/DarkRP#3076] opened 2020-12-30 16:41 UTC
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Hi, I have a problem with keeping door groups and jail positions. the admin system is - ulx. I tried everything, tell me what to do?

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment] 2020-12-30 18:01
I don't have this when I try it. Try the following:

- Look in the server log for errors. Those might prevent door groups and jail positions from loading
- Try again with no addons installed. Many people have this exact problem caused by some shitty addon.

I'm closing this issue, because I'm not responsible for the issue. You can still post updates to this issue, I'll still get notifications.

**Closed by FPtje** 2020-12-30 18:01 UTC
