### ISSUE TITLE
Disabled fadmin, cant arrest

### ISSUE THREAD

**Issue by Jonathan-5** [FPtje/DarkRP#2396] opened 2016-04-01 12:49 UTC
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Didn't change much, using stock DarkRP and DarkrpModification, simply disabled fadmin in disableddefaults.lua. The issue is I cant arrest people when Fadmin is disabled.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Attempting to arrest a player

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

Error that appears when attempting to arrest:

[ERROR] gamemodes/darkrp/gamemode/modules/police/sv_init.lua:288: attempt to call method 'FAdmin_GetGlobal' (a nil value)
  1. Call - gamemodes/darkrp/gamemode/modules/police/sv_init.lua:288
   2. unknown - gamemodes/darkrp/entities/weapons/arrest_stick/shared.lua:76

**Comment by Jonathan-5** [comment] 2016-04-01 13:09
I'm assuming the unarrest baton is also broken when Fadmin is disabled, thanks for your time on fixing this :+1:

**Comment by FPtje** [comment] 2016-04-01 15:31
That error would happen when the variable `FAdmin` is defined, but `FindMetaTable("Player").FAdmin_GetGlobal is not. That is really odd behaviour and I cannot reproduce it. Even when I disable FAdmin, arresting works fine.

I have a suspicion that some addon is defining `FAdmin`. Could you run the following command in your RCon console and tell me what happens?

```
lua_run print("printing Fadmin table") PrintTable(FAdmin) print("end FAdmin table")
```

Post the result in this issue. Either way I'm closing the issue because I cannot reproduce it. I will still get notifications of the issue when you post.

**Comment by Jonathan-5** [comment] 2016-04-01 15:43
printing Fadmin table
StartHooks:
                Popups  =       function: 0x1c115168
end FAdmin table


That's all I got

**Comment by FPtje** [comment] 2016-04-01 15:47
That shows a valid use case of redefining FAdmin if it doesn't exist yet

**Comment by FPtje** [comment] 2016-04-01 15:49
Fixed in latest

**Closed** 2016-04-01 15:50 UTC

**Comment by Jonathan-5** [comment] 2016-04-02 19:27
Thanks, I manually fixed the addon that was causing this as well.
This should hopefully fix it for others too :100:  FPTje you're the man
