### ISSUE TITLE
Traslating issue

### ISSUE THREAD

**Issue by ArankHawk** [FPtje/DarkRP#1793] opened 2015-02-19 04:46 UTC
In translation, I changed western punctuation marks (Halfwidth forms) to Chinese punctuation marks (Fullwidth forms).
If strings show up in game by pop-up notification, they will crash to desktop without errors in console.
Just display 'Dropped PlayerName from Server (PlayerName timed out)'.
For example:
```lua
lockdown_started = "市長實行了戒嚴，請立刻返回至你的住所。",

law_added = "法律已新增。",
```
If mayor initiates a lockdown or adds a law, all players in the server will crash to desktop.

And If i chat in OOC channel, one of the strings shows the original English string up.
Code:
```lua
hear_noone = "沒人聽得見你%s！",

speak_in_ooc = "在 OOC 交談",
```
In game, it shows, '沒人聽得見你speak in OOC！'.

In custom animation menu, all the animations show the original English string up.
Code:
```lua
bow = "鞠躬",
dance = "跳舞",
follow_me = "跟隨我！",
laugh = "大笑",
lion_pose = "獅子式",
nonverbal_no = "非言語拒絕",
thumbs_up = "豎起大拇指",
wave = "揮手",
```
Sorry to bother you.
And here I really appreciate you for fixing my previous issue.

**Comment by HDG-MrDeeJay** [comment] 2015-02-19 04:50
That crash may be a Garry's Mod issue, rather than a DarkRP issue. The 
rest seem like DarkRP bugs though.

**Comment by FPtje** [comment] 2015-02-19 06:26
There was this Korean guy who had the same issue: Korean notifications
would crash people. I remember him posting on Facepunch about it. Maybe
it's something that will be fixed in the next gmod update. I can't ask him
because he went to serve in the military.

**Comment by ArankHawk** [comment] 2015-02-19 06:27
OK, Thank you.

**Comment by Bo98** [comment] 2015-02-19 07:57
Does it happen to any other DLabel? Notifications is just an animated DLabel.

**Comment by FPtje** [comment] 2015-02-19 19:27
![2015-02-19_20-25-58](https://cloud.githubusercontent.com/assets/1202014/6274135/90841896-b875-11e4-8b23-106f746ea4d8.png)
Like with the Korean guy, I can't reproduce the crash. The other issues can be fixed though.

If you have any experience with Lua, you could try to see if you can find the cause. I suspect it's somewhere in DLabel or `draw.DrawText` code.

**Comment by HDG-MrDeeJay** [comment] 2015-02-19 19:37
Could have something to do with the operating system too, and its 
language setting? Some applications (such as some highschool hentai game 
that was floating around /v/ and /mlp/. for a while) require specific 
languages to be in use on the PC. Perhaps, here we are noticing somewhat 
of an inverse... idk.

**Comment by FPtje** [comment] 2015-02-19 19:38
That is very well possible, yes.

**Comment by FPtje** [comment] 2015-02-19 19:44
Alright, the animation menu and the OOC things are fixed. Here's the result:
![2015-02-19_20-43-17](https://cloud.githubusercontent.com/assets/1202014/6274454/076f59a0-b878-11e4-8ce5-634250007f52.png)
![2015-02-19_20-43-04](https://cloud.githubusercontent.com/assets/1202014/6274455/076fd72c-b878-11e4-9541-5ab0119ff01a.png)

You're a great help to me by reporting these issues. Thanks!

**Closed by FPtje** 2015-02-19 19:44 UTC

**Comment by ArankHawk** [comment] 2015-02-20 04:10
You're welcome!
