### ISSUE TITLE
Weaponchecker issue

### ISSUE THREAD

**Issue by Rezanans-wow** [FPtje/DarkRP#3051] opened 2020-09-11 16:30 UTC
Hello! I have problems with weapon checker on update. (I waited 20d and collected statistics, my players have issue with "Backing weapons". **I think old code are better.** And its on stats optimized too, and not need to change GetWeapon:

https://github.com/FPtje/DarkRP/commit/bb531405cf82120de7cedc54b5cda5cc6a7a550f

**Comment by Rezanans-wow** [comment] 2020-09-11 16:31
*30d ago all okey, my community not reporter any issue with weaponchecker. But now so many "reports"

**Comment by FPtje** [comment] 2020-09-11 16:45
And what is the issue of backing weapons?

**Comment by mcNuggets1** [comment] 2020-09-11 18:56
This literally doesn't change a fuck.
Update your server to the latest gmod version.

**Comment by FlorianLeChat** [comment] 2020-09-11 20:58
This is a strange problem compared to the changes. Unless the server has not been updated since September 2019.. so there is another problem. Otherwise, I can't understand the problem with the use of the ipairs iterator for the player's weapons. If there was a problem with that, then it would be well known, however there is nothing. So I think the problem is elsewhere.

**Comment by Kefta** [comment] 2020-09-11 22:29
You said you've collected statistics on its performance, may we see them?

**Comment by FPtje** [comment] 2020-09-13 10:10
Closing this issue, the language is so unclear that I really don't know what the problems are, what is being referred to by statistics. Besides, the mentioned commit should work on latest gmod. The most likely issue (non-sequential table returned by `:GetWeapons()`) is fixed by the latest gmod update.

**Closed by FPtje** 2020-09-13 10:10 UTC

**Comment by Kefta** [comment] 2020-09-13 17:43
It's been fixed for a while now.
