### ISSUE TITLE
Full darkrp is broke

### ISSUE THREAD

**Issue by Stasyan06** [FPtje/DarkRP#3105] opened 2021-02-20 17:06 UTC
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Hi! I found a BIG issue after some updates of gmod. The darkrp contains old functions and needs some fixes. Example: if you are Mayor you can't change the job from it because resetLaws is broke. Or when you die by mayor your job is not changing back to citizen it keeps be mayor. (In jobs.lua i set the PlayerDeath))

### How to make the bug happen
[//]: # (Become mayor and try to change to job.)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (-)
[//]: # (-)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by mcNuggets1** [comment] 2021-02-20 18:22
This doesn't seem like DarkRP broke, seems like you fucked something up.
If you would atleast attach the error you are getting so we can know for sure.

**Comment by FPtje** [comment] 2021-02-20 18:22
I cannot reproduce the errors you report. DarkRP works fine for me on the latest version of Garry's mod. Switching to mayor and back works. The command `/resetlaws` works.

Since there are no errors given, I must assume this is caused by modifications. Closing issue.

**Closed by FPtje** 2021-02-20 18:22 UTC
